### ISSUE TITLE
The application was unable to start correctly (0xc000007b)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Ryzhehvost/keyla#35] opened 2015-12-21 08:43 UTC
```
1. install keyla-0.1.9-x64-setup.exe 
2. 2 'Run keyla...' checkboxes at the end of installation are checked
3. nothing happens
4. then run keyla manually result this error:

```

Original issue reported on code.google.com by `eurusov@gmail.com` on 4 Nov 2013 at 3:16

Attachments:
* [keyla.gif](https://storage.googleapis.com/google-code-attachments/keyla/issue-35/comment-0/keyla.gif)

**Comment by Ryzhehvost** [comment] 2015-12-22 08:32
duplicate of #26

**Closed by Ryzhehvost** 2015-12-22 08:32 UTC
Labels: auto-migrated, duplicate, Priority-Medium, Type-Defect
