### ISSUE TITLE
Не различает способы ввода.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Ryzhehvost/keyla#12] opened 2015-12-21 08:43 UTC
```
Система: Windows XP SP3
Установлены русский и японский языки.
Список раскладок в опция keyla выглядит так:
 Language     Shortcut                         Use when switching 
1.Japanese                                            No
2.Japanese                                            Yes
3.Russian        Left Alt + Left Shift + 3            Yes
4.Japanese                                            No
Японский язык один, но способов ввода три. 
Два ставятся по умолчанию - Microsoft IME и Microsoft 
Natural, плюс я еще поставил Google Input, но для 
циклической смены раскладок мне нужна 
только одна из них - №2, кстати, т.к. в 
диалоге настроек keyla они все называются 
одинаково "Japanese", приходится методом тыка 
подбирать нужную). После перезапуска 
программы, из строчки №2 слетает галочка 
"Yes" и приходится каждый раз ставить вручную.
```

Original issue reported on code.google.com by `kreli...@gmail.com` on 20 Sep 2011 at 7:51

**Comment by Ryzhehvost** [comment] 2015-12-22 08:20
duplicate of #11

**Closed** 2015-12-22 08:39 UTC
Labels: auto-migrated, duplicate, enhancement, Priority-Medium
