### ISSUE TITLE
Icons don't always update

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Ryzhehvost/keyla#20] opened 2015-12-21 08:43 UTC
```
What steps will reproduce the problem?
1. Configure keyla with 2 layouts and a shortcut
2. Enable "Global layout"
3. Use the shortcut to switch layouts

What is the expected output? What do you see instead?

I expect the icons to cycle. But sometimes, the icon doesn't change.

This seems to be related to the active window. It works for 3rd party programs, 
but not for "windows accessories".  I have confirmed that while these are 
active, the icon doesn't update:
- notepad
- windows explorer
- command prompt (cmd)
- wordpad
- no active window (e.g. focus on desktop)

Note that the layout switching itself does work as expected. Just the icon 
update fails.

If I switch layouts in a non-working window (notepad) and then change focus to 
a working window (my browser), the icon updates.


When "Global layout" is disabled, the problem remains.  But the icon is updated 
when the non-working window regains focus.  For example:
In notepad: change from layout1 to layout2, icon1 stays
Focus to browser: icon1 stays (as expected, browser is still using layout1)
Focus to notepad: icon1 changes to icon2


What version of the product are you using? On what operating system?

keyla 0.1.8 on Windows 7 Home Premium 64 bit
```

Original issue reported on code.google.com by `rafh...@gmail.com` on 31 May 2012 at 8:37

**Comment by Ryzhehvost** [comment] 2015-12-22 08:27
duplicate of #36

**Closed by Ryzhehvost** 2015-12-22 08:27 UTC
Labels: auto-migrated, Can't reproduce, Priority-Low
