### ISSUE TITLE
Hotkey setting not saved correctly for language with multiple layouts

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Ryzhehvost/keyla#8] opened 2015-12-21 08:43 UTC
```
What steps will reproduce the problem?
1. Use multiple layouts for the same language, E.g. German and Dvorak layout 
with German language.
2. Assign a different shortcut to each layout in keyla, then close keyla.
3. Open keyla.

What is the expected output? What do you see instead?
The assigned shortcuts should be the same as entered previously, but
the assigned shortcut is set to the same value for all layouts.

Also, the language displayed by keyla is not the same as displayed by Windows 
language bar. It is the language of regional settings, which may be a different 
one from the keyboard layout language. Keyla should use the latter (e.g. the 
language of Dvorak layout is English, even if selected language in regional 
settings is German).

What version of the product are you using? On what operating system?
0.1.7 on Windows XP SP 3.

Please provide any additional information below.

```

Original issue reported on code.google.com by `thenl...@gmail.com` on 10 Jun 2011 at 8:39

**Comment by Ryzhehvost** [comment] 2015-12-22 08:21
duplicate of #11

**Closed by Ryzhehvost** 2015-12-22 08:21 UTC
Labels: auto-migrated, duplicate, Priority-Medium, Type-Defect
