### ISSUE TITLE
Tray icon not correct

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Ryzhehvost/keyla#34] opened 2015-12-21 08:43 UTC
```
What steps will reproduce the problem?
1. Open Windows Explorer or rename file on the desktop or use Search option in 
the Start menu
2.
3.

What is the expected output? What do you see instead?

The layout is changed when pressing (Ctrl+Shift on my PC) but the flag is not 
correct in the keyla tray icon. It does not catch the change. Even pressing 
shortcut defined in keyla does not change the icon (but the key layout is 
changed)

What version of the product are you using? On what operating system?
0.1.9.0. On Win7 64

Please provide any additional information below.

Would be nice to be able to switch to the next keyboard by clicking once on the 
icon in the tray


```

Original issue reported on code.google.com by `okt...@gmail.com` on 21 Apr 2013 at 4:49

**Comment by Ryzhehvost** [comment] 2015-12-22 08:26
duplicate of #36

**Closed by Ryzhehvost** 2015-12-22 08:26 UTC
Labels: auto-migrated, Can't reproduce, duplicate, Priority-Medium, Type-Defect
